// Generated by CoffeeScript 1.7.1
(function() {
  import getJSON from 'frontend/utils/get_json';
  import ajax from 'frontend/utils/ajax';
  import urlFor from 'frontend/utils/url_for';
  var login;

  login = function(username, password) {
    var config, container, params;
    container = Window.App.__container__;
    config = container.lookup('config:main');
    params = {
      data: {
        password: password,
        username_type: 'email',
        grant_type: 'password',
        client_id: config.get('client_id'),
        client_secret: config.get('client_secret')
      },
      type: 'POST',
      dataType: 'json',
      crossDomain: true
    };
    return ajax(urlFor('auth/token'), params);
  };

  export default login;

}).call(this);

//# sourceMappingURL=login.map
