// Generated by CoffeeScript 1.7.1
(function() {
  var ajax;

  ajax = function(url, params) {
    var args;
    args = arguments;
    return new (Ember.RSVP.Promise = function(resolve, reject) {
      $.ajax.apply($, args).then(json, status, xhr)(function() {
        if (json.error) {
          xhr.then = null;
          Ember.run(null, reject, xhr);
        } else {
          Ember.run(null, resolve, json);
        }
      }, function(xhr) {
        Ember.run(null, reject, xhr);
      });
    });
  };

  export default ajax;

}).call(this);

//# sourceMappingURL=ajax.map
