// Generated by CoffeeScript 1.7.1
(function() {
  var getJSON;

  getJSON = function(url, params) {
    var args;
    args = arguments;
    return new Ember.RSVP.Promise(function(resolve, reject) {
      return $.getJSON.apply($, args).then(function(json, status, xhr) {
        if (json.error) {
          xhr.then = null;
          Ember.run(null, reject, xhr);
        } else {
          Ember.run(null, resolve, xhr);
        }
      }, function(xhr) {
        return Ember.run(null, reject, xhr);
      });
    });
  };

  export default getJSON;

}).call(this);

//# sourceMappingURL=get_json.map
