// Generated by CoffeeScript 1.7.1
(function() {
  var unhandledRejection;

  unhandledRejection = function(reason) {
    Ember.Logger.error(reason);
    Ember.Logger.assert(reason);
    setTimeout(function() {
      throw reason;
    }, 0);
  };

  export default unhandledRejection;

}).call(this);

//# sourceMappingURL=unhandled_rejection.map
